packages:
  - packages/*
  - demos
  - docs

catalog:
  "@antfu/eslint-config": ^4.16.2
  "eslint": ^9.30.1
  "tsdown": ^0.12.9
  "typescript": ^5.8.3
  "vitest": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  "@types/node": 22.13.14