name: CI - Monorepo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-monorepo:
    name: CI - Monorepo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters in all packages
        run: pnpm -r --parallel lint

      - name: Build all packages
        run: pnpm -r --parallel build

      - name: Run tests in all packages
        run: pnpm -r --parallel test