name: CI - Monorepo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-monorepo:
    name: CI - Monorepo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate astro types
        run: pnpm --filter @cadence-mq/docs astro sync

      - name: Run quality checks
        run: pnpm check

      - name: Build packages
        run: pnpm build:packages

      - name: Run tests
        run: pnpm test

      - name: Build documentation
        run: pnpm --filter @cadence-mq/docs build
